version: '3'
services:
  nginx:
    build: ./build/nginx
    working_dir: /var/www/html/laravel
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx:/var/log/nginx
      - ./repository:/var/www/html
    ports:
      - 80:80
    networks:
      default:
        aliases:
          - api.pet-shop.test

  php8:
    build: ./build/php8
    working_dir: /var/www/html/laravel
    volumes:
      - ./config/php8/php.ini:/usr/local/etc/php/php.ini
      - ./repository:/var/www/html
    networks:
      - default

  mysql:
    build: ./build/mysql
    working_dir: /var/www/html/laravel
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./repository:/var/www/html
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - default

networks:
  default:
    driver: bridge
