version: '3'
services:
  nginx:
    build: ./build/nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx:/var/log/nginx
    ports:
      - 80:80
    networks:
      - default

  php8:
    build: ./build/php8
    volumes:
      - ./config/php8/php.ini:/usr/local/etc/php/php.ini
    networks:
      - default

  mysql:
    build: ./build/mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - default

networks:
  default:
    driver: bridge
